### ISSUE TITLE
关于CSP_DenseNet的一行代码

### ISSUE THREAD

**Issue by HuKai97** [hua1024/OpenClas#1]
Csp_DenseNet（）函数的计算num_features是不是应该要下？

![image](https://user-images.githubusercontent.com/68494594/119263125-59fa3300-bc10-11eb-87f2-af71b6e6b18c.png)

**Comment by HuKai97** [comment]
改下

**Comment by hua1024** [comment]
@coderhukai 应该已经修改过了，好久之前了，具体是哪行的
